version: "3"

services:
  app:
    volumes:
      - ./vendor:/var/www/html/vendor
    depends_on:
      - db

  db:
    image: mysql:8.0.3
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql
    command: 
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
volumes:
  dbdata:
