version: "3"

services:
  app:
    volumes: 
      - ./vendor:/var/www/html/vendor
      - ./public/.htaccess:/var/www/html/.htaccess
    depends_on:
      - db

  db:
    image: mysql:8.0.3
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
volumes:
  dbdata:
