Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Controllers\\User",
            "name": "User",
            "summary": "User\u0020controller",
            "url": "classes/App-Controllers-User.html"
        },                {
            "fqsen": "\\App\\Controllers\\User\u003A\u003AloginAction\u0028\u0029",
            "name": "loginAction",
            "summary": "Affiche\u0020la\u0020page\u0020de\u0020login",
            "url": "classes/App-Controllers-User.html#method_loginAction"
        },                {
            "fqsen": "\\App\\Controllers\\User\u003A\u003AregisterAction\u0028\u0029",
            "name": "registerAction",
            "summary": "Page\u0020de\u0020cr\u00E9ation\u0020de\u0020compte",
            "url": "classes/App-Controllers-User.html#method_registerAction"
        },                {
            "fqsen": "\\App\\Controllers\\User\u003A\u003AaccountAction\u0028\u0029",
            "name": "accountAction",
            "summary": "Affiche\u0020la\u0020page\u0020du\u0020compte",
            "url": "classes/App-Controllers-User.html#method_accountAction"
        },                {
            "fqsen": "\\App\\Controllers\\User\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "",
            "url": "classes/App-Controllers-User.html#method_register"
        },                {
            "fqsen": "\\App\\Controllers\\User\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "",
            "url": "classes/App-Controllers-User.html#method_login"
        },                {
            "fqsen": "\\App\\Controllers\\User\u003A\u003AlogoutAction\u0028\u0029",
            "name": "logoutAction",
            "summary": "Logout\u003A\u0020Delete\u0020cookie\u0020and\u0020session.\u0020Returns\u0020true\u0020if\u0020everything\u0020is\u0020okay,\notherwise\u0020turns\u0020false.",
            "url": "classes/App-Controllers-User.html#method_logoutAction"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-controllers.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        }            ]
);
